"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import json
import os
from pathlib import Path
from datetime import timedelta
from rest_framework.settings import api_settings

raw_login_timeout = os.getenv("LOGIN_TIMEOUT_VALUE", "30")
if raw_login_timeout.strip().lower() == "none":
    KNOX_TOKEN_TTL = None
else:
    try:
        KNOX_TOKEN_TTL = timedelta(minutes=int(raw_login_timeout))
    except ValueError:
        KNOX_TOKEN_TTL = timedelta(minutes=30)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv("DEBUG")))

ALLOWED_HOSTS = json.loads(os.getenv("ALLOWED_HOSTS"))

# Application definition
AUTH_USER_MODEL = "access_control.User"

INSTALLED_APPS = [
    "channels",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "knox",
    "corsheaders",
    "core",
    "pipeline",
    "import_export",
    "django_extensions",
    "colorfield",
    "theme",
    "settings",
    "dashboard",
    "access_control",
    "drf_spectacular",
    "drf_spectacular_sidecar",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "access_control.authentication.CookieTokenAuthentication",  # HttpOnly cookie auth (primary)
        "knox.auth.TokenAuthentication",  # Header auth (fallback for API clients)
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
        "core.permissions.CustomPermission",  # Custom permission class
    ),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

REST_KNOX = {
    "SECURE_HASH_ALGORITHM": "hashlib.sha512",
    "AUTH_TOKEN_CHARACTER_LENGTH": 64,
    "TOKEN_TTL": KNOX_TOKEN_TTL,
    "USER_SERIALIZER": "access_control.serializers.UserSerializer",
    "TOKEN_LIMIT_PER_USER": None,
    "AUTO_REFRESH": True,
    "MIN_REFRESH_INTERVAL": 60,  # Minimum seconds between token expiry updates (prevents excessive DB writes)
    "EXPIRY_DATETIME_FORMAT": api_settings.DATETIME_FORMAT,
    "AUTH_HEADER_PREFIX": "Bearer",
}

AUTH_COOKIE_NAME = "auth_token"
AUTH_COOKIE_SECURE = not DEBUG
AUTH_COOKIE_SAMESITE = "Lax"
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_PATH = "/"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "access_control.middleware.SlidingSessionMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "core/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"
ASGI_APPLICATION = "app.asgi.application"


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USERNAME"),
        # "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("PGBOUNCER_HOST"),
        "PORT": os.getenv("PGBOUNCER_PORT"),
    }
}

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{REDIS_HOST}:{REDIS_PORT}",
        "KEY_PREFIX": "redis_caches",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = json.loads(os.getenv("CORS_ALLOWED_ORIGINS"))

# Allow credentials (cookies) to be sent with cross-origin requests
CORS_ALLOW_CREDENTIALS = True

DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50MB

DATA_UPLOAD_MAX_NUMBER_FIELDS = 5000

BATCH_INPUT_PATH_DOCKER = "/batches"
DATASET_BATCH_INPUT_PATH = "/training-dataset"
INPUT_FILES_PATH = "/input-files"

DOCBUILDER_API_URL = os.getenv("DOCBUILDER_API_URL")
UTILITY_API_URL = os.getenv("UTILITY_API_URL")
ICAP_API_URL = os.getenv("ICAP_API_URL")
CLASSIFIER_API_URL = os.getenv("CLASSIFIER_API_URL")

DEFINITION_VERSIONS = os.getenv("DEFINITION_VERSIONS")
DEFINITION_VERSIONS = DEFINITION_VERSIONS.lower().split("|")
DEFAULT_DEFINITION_VERSION = os.getenv("DEFAULT_DEFINITION_VERSION")

# Layout similarity threshold for pattern matching using cosine similarity (0.0 to 1.0)
# Uses sentence embeddings for semantic similarity, same as Qdrant approach
LAYOUT_SIMILARITY_THRESHOLD = float(os.getenv("LAYOUT_SIMILARITY_THRESHOLD", "0.85") or "0.85")

CSRF_TRUSTED_ORIGINS = json.loads(os.getenv("CSRF_TRUSTED_ORIGINS"))

FERNET_SECRET_KEY = os.getenv("FERNET_SECRET_KEY")

CHANGE_LOGS_DOCKER_PATH = "/change_logs"

SPECTACULAR_SETTINGS = {
    "TITLE": "AIDB V6 API Documentation",
    "DESCRIPTION": "API documentation for AIDB V6",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
    },
    "SWAGGER_UI_DIST": "SIDECAR",
    "SWAGGER_UI_FAVICON_HREF": "SIDECAR",
}

RQ_QUEUES = {
    "default": {
        "HOST": os.getenv("REDIS_HOST"),
        "PORT": os.getenv("REDIS_PORT"),
        "DEFAULT_TIMEOUT": 10800,  # 3 hours
    }
}

# Channels
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(os.getenv("REDIS_HOST"), os.getenv("REDIS_PORT"))],
        },
    },
}

NOTEBOOK_ARGUMENTS = [
    "--ip",
    "0.0.0.0",
    "--port",
    "8050",
    "--allow-root",
    "--no-browser",
]

IPYTHON_ARGUMENTS = [
    "--ext",
    "django_extensions.management.notebook_extension",
    "--ext",
    "myproject.notebook_extension",
    "--debug",
]


####
# LDAP Settings
####
ENABLE_LDAP_AUTH = os.getenv("ENABLE_LDAP_AUTH", "0")

if ENABLE_LDAP_AUTH == "1":
    LDAP_SERVER_ADDRESS = os.getenv("LDAP_SERVER_ADDRESS")
    LDAP_SERVER_PORT = os.getenv("LDAP_SERVER_PORT")
    LDAP_BIND_DN = os.getenv("LDAP_BIND_DN")
    LDAP_BIND_PASSWORD = os.getenv("LDAP_BIND_PASSWORD")
    LDAP_USER_SEARCH_DN = os.getenv("LDAP_USER_SEARCH_DN")
    LDAP_GROUP_SEARCH_DN = os.getenv("LDAP_GROUP_SEARCH_DN")
    LDAP_AUTH_USER_GROUP = os.getenv("LDAP_AUTH_USER_GROUP")
    LDAP_AUTH_SUPERUSER_GROUP = os.getenv("LDAP_AUTH_SUPERUSER_GROUP")

    if DEBUG:
        print("LDAP AUTH is enabled")
        print(f"{LDAP_SERVER_ADDRESS=}")
        print(f"{LDAP_SERVER_PORT=}")
        print(f"{LDAP_BIND_DN=}")
        print(f"{LDAP_BIND_PASSWORD=}")
        print(f"{LDAP_USER_SEARCH_DN=}")
        print(f"{LDAP_GROUP_SEARCH_DN=}")
        print(f"{LDAP_AUTH_USER_GROUP=}")
        print(f"{LDAP_AUTH_SUPERUSER_GROUP=}")

    import ldap
    from django_auth_ldap.config import ActiveDirectoryGroupType, LDAPSearch

    AUTH_LDAP_SERVER_URI = f"ldap://{LDAP_SERVER_ADDRESS}:{LDAP_SERVER_PORT}"
    AUTH_LDAP_BIND_DN = LDAP_BIND_DN
    AUTH_LDAP_BIND_PASSWORD = LDAP_BIND_PASSWORD

    AUTH_LDAP_USER_SEARCH = LDAPSearch(
        LDAP_USER_SEARCH_DN, ldap.SCOPE_SUBTREE, "sAMAccountName=%(user)s"
    )

    AUTH_LDAP_USER_ATTR_MAP = {
        "username": "sAMAccountName",
        "first_name": "givenName",
        "last_name": "sn",
        "email": "mail",
    }

    AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
        LDAP_GROUP_SEARCH_DN, ldap.SCOPE_SUBTREE, "(objectCategory=Group)"
    )

    AUTH_LDAP_GROUP_TYPE = ActiveDirectoryGroupType(name_attr="cn")
    AUTH_LDAP_USER_FLAGS_BY_GROUP = {
        "is_active": LDAP_AUTH_USER_GROUP,
        "is_superuser": LDAP_AUTH_SUPERUSER_GROUP,
        "is_staff": LDAP_AUTH_SUPERUSER_GROUP,
    }

    AUTH_LDAP_FIND_GROUP_PERMS = True

    AUTHENTICATION_BACKENDS = [
        "access_control.backends.CustomLDAPBackend",
    ]

    if DEBUG:
        LOGGING = {
            "version": 1,
            "disable_existing_loggers": False,
            "handlers": {"console": {"class": "logging.StreamHandler"}},
            "loggers": {
                "django_auth_ldap": {"level": "DEBUG", "handlers": ["console"]}
            },
        }

####
# EMAIL Settings
####
SEND_EMAILS = 0

send_emails_env_value = os.getenv("SEND_EMAILS")
if send_emails_env_value:
    SEND_EMAILS = int(send_emails_env_value)

EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_PORT = os.getenv("EMAIL_PORT")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")

EMAIL_USE_TLS = False
email_use_tls_env_value = os.getenv("EMAIL_USE_TLS")
if email_use_tls_env_value:
    if email_use_tls_env_value.lower() == "true":
        EMAIL_USE_TLS = True


# Note: During developement avoid sending actual emails, so use console backend
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"

# Analyzer log
DATETIME_FORMAT = "Y-m-d H:i:s"
USE_L10N = False
SAVE_TRANSACTION_LOG = int(os.getenv("SAVE_TRANSACTION_LOG", 0))

# Django import export settings
IMPORT_EXPORT_USE_TRANSACTIONS = True

from sentence_transformers import SentenceTransformer #noqa

MODEL_PATH = "/app/models/all-MiniLM-L6-v2"
SENTENCE_TRANSFORMERS_MODEL = SentenceTransformer(MODEL_PATH , device="cpu")

# GrapeCity SpreadJS License Key
GRAPECITY_SPREADJS_LICENSE = os.getenv("GRAPECITY_SPREADJS_LICENSE", "")