FROM registry.access.redhat.com/ubi8/nodejs-16:1-37

WORKDIR /app

USER 0

COPY package*.json /app/

RUN chown -R 1001:0 ./

USER 1001

RUN npm install

COPY . .

EXPOSE 8080

CMD [ "npm", "run", "serve" ]