# Generated by Django 4.0.2 on 2024-03-27 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_alter_country_name_alter_project_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='user',
            name='projects',
        ),
        migrations.CreateModel(
            name='ProjectCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', models.ManyToManyField(to='access_control.Country')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access_control.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Project Countries',
            },
        ),
    ]
