# Generated by Django 4.0.2 on 2024-04-03 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_profile_email_domains_alter_profile_email_from'),
        ('access_control', '0003_alter_user_options_remove_user_countries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcountry',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.project'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
