# Generated by Django 4.0.2 on 2024-04-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_country'),
        ('access_control', '0004_alter_projectcountry_project_delete_project'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='projectcountry',
            name='countries',
            field=models.ManyToManyField(to='core.Country'),
        ),
    ]
