# Generated by Django 4.0.2 on 2022-08-22 07:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataCleanupConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "persist_batch_status_for_days",
                    models.PositiveIntegerField(
                        help_text="Persist Batch status for Number of days",
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
                (
                    "persist_prod_batch_for_days",
                    models.PositiveIntegerField(
                        help_text="Persist Processing (Production) Batch for Number of days",
                        validators=[django.core.validators.MaxValueValidator(30)],
                    ),
                ),
            ],
        ),
    ]
