# Generated by Django 4.0.2 on 2022-08-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datacleanupconfig",
            name="dump_batch_status_csv",
            field=models.BooleanField(
                default=True,
                help_text="if selected, To-be deleted batch status items will be saved as CSV to Batch Folder",
            ),
        ),
    ]
