# Generated by Django 4.0.2 on 2022-09-17 09:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_datacleanupconfig_dump_batch_status_csv"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datacleanupconfig",
            name="persist_batch_status_for_days",
            field=models.PositiveIntegerField(
                help_text="Persist Batch status for Number of days",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
        migrations.AlterField(
            model_name="datacleanupconfig",
            name="persist_prod_batch_for_days",
            field=models.PositiveIntegerField(
                help_text="Persist Processing (Production) Batch for Number of days",
                validators=[django.core.validators.MaxValueValidator(90)],
            ),
        ),
    ]
