# Generated by Django 4.0.2 on 2022-09-22 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "settings",
            "0003_alter_datacleanupconfig_persist_batch_status_for_days_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DataExportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("export_system_name", models.CharField(max_length=100)),
                ("export_system_url", models.CharField(max_length=250)),
            ],
        ),
    ]
