# Generated by Django 4.0.2 on 2022-09-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_dataexportconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dataexportconfig",
            name="export_system_url",
            field=models.CharField(
                help_text="Should not end with slash (/)", max_length=250
            ),
        ),
    ]
