# Generated by Django 4.0.2 on 2022-09-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_alter_dataexportconfig_export_system_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataImportConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_name",
                    models.CharField(
                        help_text="Name of the system which can send data to this system",
                        max_length=100,
                    ),
                ),
                (
                    "auth_key",
                    models.CharField(
                        help_text="This key is used to verify if request sender is valid.",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dataexportconfig",
            name="export_system_auth_key",
            field=models.CharField(
                default="",
                help_text="Copy Auth Key from Destination System",
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
