# Generated by Django 4.0.2 on 2025-08-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=50)),
                ('service', models.CharField(blank=True, max_length=50)),
                ('mailbox', models.EmailField(blank=True, max_length=254, null=True)),
                ('file_name', models.CharField(blank=True, max_length=500, null=True)),
                ('path', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='queued', max_length=50)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
