# Generated by Django 5.1.4 on 2025-09-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processlog",
            name="error",
        ),
        migrations.AddField(
            model_name="processlog",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="processlog",
            name="remarks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="processlog",
            name="file_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
