# Generated by Django 5.1.4 on 2025-10-01 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_processlog_error_processlog_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="processlog",
            name="batch_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="processlog",
            name="queue_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
