# Generated by Django 4.0.2 on 2026-01-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(blank=True, help_text='Code/text content', null=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt used for processing', null=True)),
                ('process', models.TextField(blank=True, help_text='Process definition or name', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Post Processes',
                'ordering': ['-created_at'],
            },
        ),
    ]
