# Generated by Django 4.0.2 on 2026-01-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_masterdictionary'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(blank=True, default=list, null=True)),
                ('prompt', models.TextField(blank=True, help_text='Prompt used for processing', null=True)),
                ('unique_hash', models.CharField(blank=True, help_text='Unique hash of the prompt', max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Prompt Dictionaries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='MasterDictionary',
        ),
        migrations.AddField(
            model_name='postprocess',
            name='unique_hash',
            field=models.CharField(blank=True, help_text='Unique hash of the process', max_length=255, null=True),
        ),
    ]
