# Generated by Django 4.0.2 on 2026-01-19 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_promptdictionary_delete_masterdictionary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promptdictionary',
            name='data',
        ),
    ]
