FROM docker.artifactory.dhl.com/ubi8/python-39:1-48

#please do not remove - start
COPY .pypirc /app/
COPY .pip/pip.conf /app/
COPY .pip/pip.conf  ~/.pip/pip.conf
#please do not remove - end 

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

USER 0

RUN chmod +x ./init-scripts/*

USER 1001
