# Generated by Django 4.0.2 on 2024-08-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.CharField(blank=True, max_length=30, null=True)),
                ('data', models.JSONField(blank=True, default=dict, null=True)),
                ('manual_classification_data', models.JSONField(blank=True, default=dict, null=True)),
            ],
            options={
                'verbose_name_plural': 'Custom Categories',
            },
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
    ]
