# Generated by Django 4.0.2 on 2024-08-07 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customcategory_delete_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcategory',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
