# Generated by Django 4.0.2 on 2025-02-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customcategory_created_at_customcategory_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
