export default {
  settings: {
    options: {
      'options-keys': { items: [] },
      'options-meta-root-type': { items: [] },
      'options-mapped-keys': { items: [] },
      'options-col-type': { items: [] },
      'options-col-modType': { items: [] },
    },
    keyQualifiers: [],
    compoundKeys: [],
    aIAgents: [
      {
        id: 1,
        icon: 'TruckIcon',
        type: 'Data Consolidation Agent',
        title: 'CDZ Data Modification Agent',
        disabled: false,
        selected: false,
        description: 'Modifies and consolidates data based on field precedence and user-defined rules',
      },
      {
        id: 2,
        icon: 'DollarSignIcon',
        type: 'Classification Agent',
        title: 'HBL MBL Agent',
        disabled: false,
        selected: false,
        description: 'Determines if sea waybill is HBL or MBL by matching issuer, consignee, and shipper',
      },
      {
        id: 3,
        icon: 'UserCheckIcon',
        type: 'Data Validation',
        title: 'Entity Validator',
        disabled: false,
        selected: false,
        description: 'Validates entity information and ensures data integrity across systems',
      },
      {
        id: 4,
        icon: 'CpuIcon',
        type: 'type-4',
        title: 'Agent-4',
        disabled: true,
        selected: false,
        description: 'description-4',
      },
      {
        id: 5,
        icon: 'BarChartIcon',
        type: 'type-5',
        title: 'Agent-5',
        disabled: true,
        selected: false,
        description: 'description-5',
      },
      {
        id: 6,
        icon: 'LockIcon',
        type: 'type-6',
        title: 'Agent-6',
        disabled: true,
        selected: false,
        description: 'description-6',
      },
      {
        id: 7,
        icon: 'GitMergeIcon',
        type: 'type-7',
        title: 'Agent-7',
        disabled: true,
        selected: false,
        description: 'description-7',
      },
      {
        id: 8,
        icon: 'ActivityIcon',
        type: 'type-8',
        title: 'Agent-8',
        disabled: true,
        selected: false,
        description: 'description-8',
      },
      {
        id: 9,
        icon: 'DatabaseIcon',
        type: 'type-9',
        title: 'Agent-9',
        disabled: true,
        selected: false,
        description: 'description-9',
      },
      {
        id: 10,
        icon: 'FileTextIcon',
        type: 'type-10',
        title: 'Agent-10',
        disabled: true,
        selected: false,
        description: 'description-10',
      },
    ],
    otherSettings: {
      ocr_settings: {
        engine_type: 'internal',
      },
      classifier_settings: {
        automatic_splitting: false,
      },
    },
    inputChannels: {
      email: {
        enabled: false,
        config: {},
      },
      api: {
        enabled: false,
        config: {},
      },
      onedrive: {
        enabled: false,
        config: {},
      },
      sharepoint: {
        enabled: false,
        config: {},
      },
    },
    outputChannels: {
      api: {
        enabled: false,
        config: {},
      },
      outputChannelTypes: [],
    },
  },
}
