# Generated by Django 4.0.2 on 2022-07-16 07:24

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ThemeSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo_light_mode",
                    models.ImageField(blank=True, null=True, upload_to="theme/logo"),
                ),
                (
                    "logo_dark_mode",
                    models.ImageField(blank=True, null=True, upload_to="theme/logo"),
                ),
                (
                    "header_color_light_mode",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                    ),
                ),
                (
                    "header_color_dark_mode",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                    ),
                ),
            ],
        ),
    ]
