# Generated by Django 4.0.2 on 2022-07-18 08:06

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="themesetting",
            name="app_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="app_title_color_dark_mode",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
        migrations.AddField(
            model_name="themesetting",
            name="app_title_color_light_mode",
            field=colorfield.fields.ColorField(
                blank=True,
                default=None,
                image_field=None,
                max_length=18,
                null=True,
                samples=None,
            ),
        ),
    ]
