# Generated by Django 4.0.2 on 2023-10-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_themesetting_app_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='theme/favicon'),
        ),
    ]
