# Generated by Django 5.1.4 on 2025-05-01 12:32

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_themesetting_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themesetting',
            name='app_title_color_dark_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='app_title_color_light_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='header_color_dark_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AlterField(
            model_name='themesetting',
            name='header_color_light_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
