# Generated by Django 5.1.4 on 2025-08-13 08:50

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_alter_themesetting_app_title_color_dark_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='themesetting',
            name='header_text_color_dark_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='themesetting',
            name='header_text_color_light_mode',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=25, null=True, samples=None),
        ),
    ]
