FROM aidbdockers/backend-base:3

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1
ENV TRANSFORMERS_OFFLINE=1
ENV HF_DATASETS_OFFLINE=1

WORKDIR /app

COPY requirements.txt .

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

USER 0

RUN mkdir /app/static

RUN chgrp -R 0 /app/static && \
    chmod -R g=u /app/static

RUN mkdir -p /app/media

RUN chgrp -R 0 /app/media && \
    chmod -R g=u /app/media


RUN chmod +x ./init-scripts/*

USER 1001
