# Generated by Django 4.0.2 on 2022-02-22 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vendor", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("columns", models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
