# Generated by Django 4.0.2 on 2022-02-22 12:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_definition_created_at_definition_updated_at"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="definition",
            unique_together={("vendor", "type")},
        ),
    ]
