# Generated by Django 4.0.2 on 2022-02-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_definition_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefinitionSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
            ],
        ),
    ]
