# Generated by Django 4.0.2 on 2022-02-22 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_definitionsettings"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="definitionsettings",
            options={"verbose_name_plural": "Definition Settings"},
        ),
    ]
