# Generated by Django 4.0.2 on 2022-03-02 04:51

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_definitionsettings_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="definition",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="definition",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("vendor"),
                django.db.models.functions.text.Lower("type"),
                name="vendor_key_unique",
            ),
        ),
    ]
