# Generated by Django 4.0.2 on 2022-03-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_definition_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Batch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("ra_json", models.JSONField(blank=True, default=dict)),
                ("data_json", models.JSONField(blank=True, default=dict)),
                ("info_json", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Batches",
            },
        ),
    ]
