# Generated by Django 4.0.2 on 2022-03-05 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_batch"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="type",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="batch",
            name="vendor",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
