# Generated by Django 4.0.2 on 2022-03-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_batch_type_batch_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="vendor",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
