# Generated by Django 4.0.2 on 2022-03-14 05:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_batch_vendor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="definition",
            old_name="meta",
            new_name="models",
        ),
    ]
