# Generated by Django 4.0.2 on 2022-03-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_rename_meta_definition_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="models",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
