# Generated by Django 4.0.2 on 2022-03-18 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_definition_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("event_time", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Batch Status",
            },
        ),
    ]
