# Generated by Django 4.0.2 on 2022-03-26 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_batchstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
