# Generated by Django 4.0.2 on 2022-03-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_definition_keys"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchstatus",
            name="message",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
