# Generated by Django 4.0.2 on 2022-04-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_batchstatus_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="definition",
            old_name="keys",
            new_name="key",
        ),
        migrations.RemoveField(
            model_name="definition",
            name="columns",
        ),
        migrations.RemoveField(
            model_name="definition",
            name="models",
        ),
        migrations.AddField(
            model_name="definition",
            name="table",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
