# Generated by Django 4.0.2 on 2022-04-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_rename_keys_definition_key_remove_definition_columns_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="key",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="definition",
            name="table",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
