# Generated by Django 4.0.2 on 2022-04-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_alter_definition_key_alter_definition_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="definition",
            name="vendor_key_unique",
        ),
        migrations.AddField(
            model_name="batch",
            name="mode",
            field=models.CharField(default="production", max_length=100),
        ),
        migrations.AddField(
            model_name="batch",
            name="profile_id",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="definition",
            name="profile_id",
            field=models.CharField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
