# Generated by Django 4.0.2 on 2022-04-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_remove_definition_vendor_key_unique_batch_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="definition",
            name="vendor",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
