# Generated by Django 4.0.2 on 2022-04-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_alter_definition_type_alter_definition_vendor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="profile_id",
        ),
        migrations.AlterField(
            model_name="definition",
            name="id",
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
