# Generated by Django 4.0.2 on 2022-04-20 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_remove_definition_profile_id_alter_definition_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="batch",
            old_name="profile_id",
            new_name="definition_id",
        ),
    ]
