# Generated by Django 4.0.2 on 2022-04-20 09:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_rename_profile_id_batch_definition_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="batch",
            name="info_json",
        ),
    ]
