# Generated by Django 4.0.2 on 2022-04-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_remove_batch_info_json"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="definition_id",
            field=models.CharField(default="", max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="definition",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
