# Generated by Django 4.0.2 on 2022-05-04 05:57

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_definition_definition_id_alter_definition_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="definition_id",
            field=models.CharField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="definition",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("definition_id"),
                django.db.models.functions.text.Lower("type"),
                name="unique_definition_id_and_type",
            ),
        ),
    ]
