# Generated by Django 4.0.2 on 2022-05-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0023_alter_definition_definition_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="type",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="definition",
            name="vendor",
            field=models.CharField(max_length=100),
        ),
    ]
