# Generated by Django 4.0.2 on 2022-05-13 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0024_alter_definition_type_alter_definition_vendor"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_value", models.CharField(max_length=100)),
                ("translated_value", models.CharField(max_length=100)),
                ("type", models.CharField(max_length=100)),
                ("method", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.definition",
                    ),
                ),
            ],
        ),
    ]
