# Generated by Django 4.0.2 on 2022-07-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0025_translationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchstatus",
            name="action",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
