# Generated by Django 4.0.2 on 2022-08-09 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_definedkey"),
    ]

    operations = [
        migrations.AddField(
            model_name="definedkey",
            name="label",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
