# Generated by Django 4.0.2 on 2022-08-09 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0028_definedkey_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definedkey",
            name="label",
            field=models.CharField(max_length=250),
        ),
    ]
