# Generated by Django 4.0.2 on 2022-08-09 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0029_alter_definedkey_label"),
    ]

    operations = [
        migrations.CreateModel(
            name="DraftDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table", models.JSONField(blank=True, default=dict)),
                ("key", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.definition",
                    ),
                ),
            ],
        ),
    ]
