# Generated by Django 4.0.2 on 2022-08-13 04:29
# Standard migration is updated to handle mode change (production to processing)

from django.db import migrations, models


def replace_production_to_processing(apps, schema_editor):
    Batch = apps.get_model("core", "Batch")
    Batch.objects.filter(mode="production").update(mode="processing")


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_draftdefinition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="mode",
            field=models.CharField(default="processing", max_length=100),
        ),
        # Handle DB record changes
        migrations.RunPython(replace_production_to_processing),
    ]
