# Generated by Django 4.0.2 on 2022-08-19 07:03
# This migration is modified to handle DB record changes
from django.db import migrations, models


def copy_definition_to_draft(apps, schema_editor):
    """Copy values of original definition to draft definition"""
    Definition = apps.get_model("core", "Definition")
    for definition in Definition.objects.all().iterator():
        definition.draft_table = definition.table
        definition.draft_key = definition.key
        definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0031_alter_batch_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="draft_key",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="definition",
            name="draft_table",
            field=models.JSONField(blank=True, default=dict),
        ),
        # Handle DB record changes
        migrations.RunPython(copy_definition_to_draft),
    ]
