# Generated by Django 4.0.2 on 2022-08-22 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0032_definition_draft_key_definition_draft_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DraftDefinition",
        ),
    ]
