# Generated by Django 4.0.2 on 2022-07-09
# Standard migration is updated to handle DB Record changes

import uuid

from django.db import migrations


def update_key_items(apps, schema_editor):
    Definition = apps.get_model("core", "Definition")

    definitions = Definition.objects.all().iterator()
    for definition in definitions:
        key = definition.key
        draft_key = definition.draft_key

        updated = False
        if key:
            if "items" in key.keys():
                key_items = key["items"]

                final_key_items = []
                for i in key_items:
                    if "id" in i.keys():
                        final_key_items.append(i)
                    else:
                        new_key_item = i.copy()
                        new_key_item["id"] = str(uuid.uuid4())
                        final_key_items.append(new_key_item)
                        updated = True

                if updated is True:
                    definition.key["items"] = final_key_items

        draft_updated = False
        if draft_key:
            if "items" in draft_key.keys():
                draft_key_items = draft_key["items"]

                final_draft_key_items = []
                for i in draft_key_items:
                    if "id" in i.keys():
                        final_draft_key_items.append(i)
                    else:
                        new_key_item = i.copy()
                        new_key_item["id"] = str(uuid.uuid4())
                        final_draft_key_items.append(new_key_item)
                        draft_updated = True

                if draft_updated is True:
                    definition.draft_key["items"] = final_draft_key_items

        if updated or draft_updated:
            definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0033_delete_draftdefinition"),
    ]

    operations = [
        # Handle DB record changes
        migrations.RunPython(update_key_items),
    ]
