# Generated by Django 4.0.2 on 2022-09-09
# Standard migration is updated to handle DB Record changes

from django.db import migrations


def update_key_rule_items(apps, schema_editor):
    Definition = apps.get_model("core", "Definition")

    definitions = Definition.objects.all().iterator()
    for definition in definitions:
        key = definition.key
        draft_key = definition.draft_key

        updated = False
        if key:
            if "ruleItems" in key.keys():
                ruleItems = key["ruleItems"]
                if len(ruleItems) > 0:
                    final_rule_items = []

                    for ruleItem in ruleItems:
                        temp_rule_item = ruleItem.copy()
                        temp_rule_item["rules"] = []

                        rules = ruleItem["rules"]
                        for rule in rules:
                            rule_type = rule["type"]
                            if rule_type == "replaceValue":
                                if not isinstance(rule["inputs"]["value"], dict):
                                    temp_rule = rule.copy()
                                    temp_rule["inputs"]["value"] = {
                                        "type": "string",
                                        "value": temp_rule["inputs"]["value"],
                                    }

                                    updated = True
                                    temp_rule_item["rules"].append(temp_rule)
                                else:
                                    temp_rule_item["rules"].append(rule)
                            else:
                                temp_rule_item["rules"].append(rule)

                        final_rule_items.append(temp_rule_item)

                    if updated is True:
                        definition.key["ruleItems"] = final_rule_items

        draft_updated = False
        if draft_key:
            if "ruleItems" in draft_key.keys():
                ruleItems = draft_key["ruleItems"]
                if len(ruleItems) > 0:
                    final_rule_items = []

                    for ruleItem in ruleItems:
                        temp_rule_item = ruleItem.copy()
                        temp_rule_item["rules"] = []

                        rules = ruleItem["rules"]
                        for rule in rules:
                            rule_type = rule["type"]
                            if rule_type == "replaceValue":
                                if not isinstance(rule["inputs"]["value"], dict):
                                    temp_rule = rule.copy()
                                    temp_rule["inputs"]["value"] = {
                                        "type": "string",
                                        "value": temp_rule["inputs"]["value"],
                                    }

                                    draft_updated = True
                                    temp_rule_item["rules"].append(temp_rule)
                                else:
                                    temp_rule_item["rules"].append(rule)
                            else:
                                temp_rule_item["rules"].append(rule)

                        final_rule_items.append(temp_rule_item)

                    if draft_updated is True:
                        definition.draft_key["ruleItems"] = final_rule_items

        if updated or draft_updated:
            definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0034_update_keys_data"),
    ]

    operations = [
        # Handle DB record changes
        migrations.RunPython(update_key_rule_items),
    ]
