# Generated by Django 4.0.2 on 2022-09-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0035_update_replaceValue_rule"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="sub_path",
            field=models.CharField(default="", max_length=250),
        ),
    ]
