# Generated by Django 4.0.2 on 2022-09-30
# Standard migration is updated to handle DB Record changes

from django.db import migrations

label_to_be_updated = {
    "totalGrossWeight": "grossWeight",
    "totalPackageCount": "packageCount",
    "totalVolume": "volume",
    "totalNetWeight": "netWeight",
}

label_to_be_updated_keys = label_to_be_updated.keys()


def update_key_items(apps, schema_editor):
    Definition = apps.get_model("core", "Definition")

    definitions = Definition.objects.all().iterator()
    for definition in definitions:
        key = definition.key
        draft_key = definition.draft_key
        updated = False
        if key:
            if "items" in key.keys():
                items = key["items"]
                final_items = []

                for item in items:
                    key_label = item["keyLabel"]
                    if key_label in label_to_be_updated_keys:
                        temp_item = item.copy()
                        temp_item["keyLabel"] = label_to_be_updated[key_label]
                        final_items.append(temp_item)
                        updated = True
                    else:
                        final_items.append(item)

                if updated is True:
                    definition.key["items"] = final_items

        draft_updated = False
        if draft_key:
            if "items" in draft_key.keys():
                items = draft_key["items"]
                final_items = []

                for item in items:
                    key_label = item["keyLabel"]
                    if key_label in label_to_be_updated_keys:
                        temp_item = item.copy()
                        temp_item["keyLabel"] = label_to_be_updated[key_label]
                        final_items.append(temp_item)
                        draft_updated = True
                    else:
                        final_items.append(item)

                if draft_updated is True:
                    definition.draft_key["items"] = final_items

        if updated or draft_updated:
            definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_batch_sub_path"),
    ]

    operations = [
        # Handle DB record changes
        migrations.RunPython(update_key_items),
    ]
