# Generated by Django 4.0.2 on 2022-10-03
# Standard migration is updated to handle DB Record changes

from django.db import migrations


def update_table_columns(apps, schema_editor):
    Definition = apps.get_model("core", "Definition")

    definitions = Definition.objects.all().iterator()
    for definition in definitions:
        table = definition.table
        draft_table = definition.draft_table
        updated = False
        if table:
            if "columns" in table.keys():
                columns = table["columns"]
                final_columns = []

                for column in columns:
                    location = column.get("location", "")
                    if location == "bellow line":
                        temp_column = column.copy()
                        temp_column["location"] = "below line"
                        final_columns.append(temp_column)
                        updated = True
                    else:
                        final_columns.append(column)

                if updated is True:
                    definition.table["columns"] = final_columns

        draft_updated = False
        if draft_table:
            if "columns" in draft_table.keys():
                columns = draft_table["columns"]
                final_columns = []

                for column in columns:
                    location = column.get("location", "")
                    if location == "bellow line":
                        temp_column = column.copy()
                        temp_column["location"] = "below line"
                        final_columns.append(temp_column)
                        draft_updated = True
                    else:
                        final_columns.append(column)

                if draft_updated is True:
                    definition.draft_table["columns"] = final_columns

        if updated or draft_updated:
            definition.save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_update_key_items"),
    ]

    operations = [
        # Handle DB record changes
        migrations.RunPython(update_table_columns),
    ]
