# Generated by Django 4.0.2 on 2022-10-05 12:22

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_update_table_columns"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="data",
            field=models.JSONField(blank=True, default=core.models.default_definition),
        ),
    ]
