# Generated by Django 4.0.2 on 2022-10-06 06:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0040_restructure_definition"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="draft_key",
        ),
        migrations.RemoveField(
            model_name="definition",
            name="draft_table",
        ),
        migrations.RemoveField(
            model_name="definition",
            name="key",
        ),
        migrations.RemoveField(
            model_name="definition",
            name="table",
        ),
    ]
