# Generated by Django 4.0.2 on 2022-10-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0041_remove_definition_draft_key_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterDictionary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Master Dictionaries",
            },
        ),
    ]
