# Generated by Django 4.0.2 on 2022-11-24 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0042_masterdictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="cw1",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="definition",
            name="use_oracle",
            field=models.BooleanField(default=False),
        ),
    ]
