# Generated by Django 4.0.2 on 2023-01-10 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0043_definition_cw1_definition_use_oracle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="definition",
            name="use_oracle",
        ),
    ]
