# Generated by Django 4.0.2 on 2023-02-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0044_remove_definition_use_oracle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="cw1",
            field=models.BooleanField(default=True),
        ),
    ]
