# Generated by Django 4.0.2 on 2023-05-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0045_alter_definition_cw1"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="extension",
            field=models.CharField(default=".pdf", max_length=20),
            preserve_default=False,
        ),
    ]
