# Generated by Django 4.0.2 on 2023-05-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0046_batch_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="project",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
