# Generated by Django 4.0.2 on 2023-07-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0047_batch_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailBatch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Email Batches",
            },
        ),
    ]
