# Generated by Django 4.0.2 on 2023-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0048_emailbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="email_from",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="emailbatch",
            name="email_subject",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emailbatch",
            name="email_to",
            field=models.CharField(default="", max_length=255),
        ),
    ]
