# Generated by Django 4.0.2 on 2023-07-13 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0049_emailbatch_email_from_emailbatch_email_subject_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="sub_path",
            field=models.CharField(default="", max_length=250),
        ),
    ]
