# Generated by Django 4.0.2 on 2023-07-18 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0050_emailbatch_sub_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailbatch",
            name="sub_path",
        ),
    ]
