# Generated by Django 4.0.2 on 2023-07-24 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_profile_exception_handling_alter_profile_project"),
        ("core", "0051_remove_emailbatch_sub_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="definition",
            name="profile_doc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.profiledocument",
            ),
        ),
    ]
