# Generated by Django 4.0.2 on 2023-07-25 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_profiledocument_unique_profile_and_doc_type"),
        ("core", "0052_definition_profile_doc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="profile_doc",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="dashboard.profiledocument",
            ),
        ),
    ]
