# Generated by Django 4.0.2 on 2023-08-02 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0053_alter_definition_profile_doc"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailToBatchLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=30)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.emailbatch",
                    ),
                ),
            ],
        ),
    ]
