# Generated by Django 4.0.2 on 2023-08-02 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0054_emailtobatchlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtobatchlink",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch_links",
                to="core.emailbatch",
            ),
        ),
    ]
