# Generated by Django 4.0.2 on 2023-08-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_profiledocument_unique_profile_and_doc_type"),
        ("core", "0055_alter_emailtobatchlink_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailParsedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("path", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=20)),
                ("batch_id", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_documents",
                        to="core.emailbatch",
                    ),
                ),
                (
                    "matched_profile_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.profiledocument",
                    ),
                ),
            ],
        ),
    ]
