# Generated by Django 4.0.2 on 2023-08-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_profiledocument_unique_profile_and_doc_type"),
        ("core", "0056_emailparseddocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="matched_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dashboard.profile",
            ),
        ),
    ]
