# Generated by Django 4.0.2 on 2023-08-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0058_fill_matched_profiles"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="email_cc",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="emailbatch",
            name="email_to",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
