# Generated by Django 4.0.2 on 2023-09-20 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0059_emailbatch_email_cc_alter_emailbatch_email_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="atm_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
