# Generated by Django 4.0.2 on 2023-10-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_outputjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='status',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
