# Generated by Django 4.0.2 on 2023-10-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_batch_status_emailbatch_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
