# Generated by Django 4.0.2 on 2023-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_batch_confirmation_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailbatch',
            name='matched_profile',
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='matched_profile_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
