# Generated by Django 4.0.2 on 2023-11-08 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_emailbatch_matched_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='assembly_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
