# Generated by Django 4.0.2 on 2023-11-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_remove_emailbatch_matched_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='job_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
