# Generated by Django 4.0.2 on 2023-11-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_batch_job_id'),
        ('core', '0065_emailbatch_assembly_triggered'),
    ]

    operations = [
    ]
