# Generated by Django 4.0.2 on 2023-11-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_merge_20231108_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='verification_status',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
