# Generated by Django 4.0.2 on 2023-11-30 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_emailbatch_verification_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefinitionSettings',
            new_name='ApplicationSettings',
        ),
    ]
