# Generated by Django 4.0.2 on 2023-12-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_rename_definitionsettings_applicationsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationsettings',
            options={'verbose_name_plural': 'Application Settings'},
        ),
    ]
