# Generated by Django 4.0.2 on 2023-12-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_alter_applicationsettings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='customs_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
