# Generated by Django 4.0.2 on 2023-12-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_emailbatch_customs_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchstatus',
            name='sub_message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
