# Generated by Django 4.0.2 on 2024-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_batchstatus_sub_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtobatchlink',
            name='classified',
            field=models.BooleanField(default=False),
        ),
    ]
