# Generated by Django 4.0.2 on 2024-03-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_emailtobatchlink_classified'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailparseddocument',
            name='splitted',
            field=models.BooleanField(default=False),
        ),
    ]
