# Generated by Django 4.0.2 on 2024-03-29 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_emailparseddocument_splitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailparseddocument',
            name='splitted',
        ),
        migrations.RemoveField(
            model_name='emailtobatchlink',
            name='classified',
        ),
    ]
