# Generated by Django 4.0.2 on 2024-04-01 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailparseddocument",
            name="splitted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emailtobatchlink",
            name="classified",
            field=models.BooleanField(default=False),
        ),
    ]
