# Generated by Django 4.0.2 on 2024-06-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_emailparseddocument_splitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtobatchlink',
            name='mode',
            field=models.CharField(default='', max_length=30),
        ),
    ]
