# Generated by Django 4.0.2 on 2024-07-19 21:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_emailtobatchlink_mode'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_id_and_type',
        ),
        migrations.AddField(
            model_name='batch',
            name='name_matching_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='definition',
            name='name_matching_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('definition_id'), django.db.models.functions.text.Lower('type'), django.db.models.functions.text.Lower('name_matching_text'), name='unique_definition_id_type_and_name_matching'),
        ),
    ]
