# Generated by Django 4.0.2 on 2024-08-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_update_existing_definitions_and_batches'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtobatchlink',
            name='uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
