# Generated by Django 4.0.2 on 2024-08-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_emailtobatchlink_uploaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='confirmation_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
