# Generated by Django 4.0.2 on 2024-08-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_emailbatch_confirmation_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="shipment_status_url",
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
