# Generated by Django 4.0.2 on 2024-08-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0082_emailbatch_shipment_status_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainBatch",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "matched_profile_name",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("job_id", models.CharField(blank=True, max_length=50, null=True)),
                ("selected_doc_ids", models.JSONField(blank=True, default=list)),
                (
                    "parsed_file_type",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                ("ra_json", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(blank=True, default="", max_length=25, null=True),
                ),
                (
                    "manual_classification_status",
                    models.CharField(blank=True, default="", max_length=10, null=True),
                ),
                (
                    "manual_classification_data",
                    models.JSONField(blank=True, default=list),
                ),
                ("file_identifiers", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Train Batches",
            },
        ),
        migrations.CreateModel(
            name="TrainToBatchLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("batch_id", models.CharField(max_length=30)),
                ("classified", models.BooleanField(default=False)),
                ("uploaded", models.BooleanField(default=False)),
                ("mode", models.CharField(default="", max_length=30)),
                (
                    "train_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batch_links",
                        to="core.trainbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainParsedDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("path", models.CharField(max_length=1000)),
                ("type", models.CharField(max_length=20)),
                ("batch_id", models.CharField(blank=True, max_length=30, null=True)),
                ("splitted", models.BooleanField(default=False)),
                (
                    "matched_profile_doc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.profiledocument",
                    ),
                ),
                (
                    "train_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parsed_documents",
                        to="core.trainbatch",
                    ),
                ),
            ],
        ),
    ]
