# Generated by Django 4.0.2 on 2024-09-05 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_training_page_transformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='api_response',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='api_triggered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='doc_upload_triggered',
            field=models.BooleanField(default=False),
        ),
    ]
