# Generated by Django 4.0.2 on 2024-09-20 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_emailbatch_api_response_emailbatch_api_triggered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='api_retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='assembled_results',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
