# Generated by Django 4.0.2 on 2024-10-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_emailbatch_api_retry_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='additional_docs_to_upload',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
