# Generated by Django 4.0.2 on 2024-10-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_emailbatch_additional_docs_to_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainbatch",
            name="file_ext_list",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
