# Generated by Django 4.0.2 on 2024-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_trainbatch_file_ext_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_batch', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_process_s', models.DateTimeField(blank=True, null=True)),
                ('transaction_uploading_s', models.DateTimeField(blank=True, null=True)),
                ('transaction_uploading_e', models.DateTimeField(blank=True, null=True)),
                ('re_process_email_batches_s', models.DateTimeField(blank=True, null=True)),
                ('time_to_queued', models.DateTimeField(blank=True, null=True)),
                ('email_parsing_s', models.DateTimeField(blank=True, null=True)),
                ('profile_matching_s', models.DateTimeField(blank=True, null=True)),
                ('profile_matching_e', models.DateTimeField(blank=True, null=True)),
                ('email_parsing_e', models.DateTimeField(blank=True, null=True)),
                ('supporting_batch_creation_time', models.JSONField(blank=True, default=list)),
                ('datacap_batch_creating_s', models.JSONField(blank=True, default=list)),
                ('datacap_batch_creating_e', models.JSONField(blank=True, default=list)),
                ('transaction_completion_time', models.DateTimeField(blank=True, null=True)),
                ('datacap_api_callback_time', models.DateTimeField(blank=True, null=True)),
                ('classification_process_queued_time', models.DateTimeField(blank=True, null=True)),
                ('classification_process_s', models.JSONField(blank=True, default=list)),
                ('document_matching_s', models.JSONField(blank=True, default=list)),
                ('document_matching_e', models.JSONField(blank=True, default=list)),
                ('batch_splitting_s', models.JSONField(blank=True, default=list)),
                ('batch_splitting_e', models.JSONField(blank=True, default=list)),
                ('batch_creation_time', models.JSONField(blank=True, default=list)),
                ('upload_batch_process_time', models.JSONField(blank=True, default=list)),
                ('classification_process_e', models.JSONField(blank=True, default=list)),
                ('assembly_process_s', models.DateTimeField(blank=True, null=True)),
                ('transaction_result_generated_time', models.DateTimeField(blank=True, null=True)),
                ('api_call_s', models.DateTimeField(blank=True, null=True)),
                ('each_api_call_s', models.JSONField(blank=True, default=list)),
                ('retry_each_api_time', models.JSONField(blank=True, default=list)),
                ('each_api_call_e', models.JSONField(blank=True, default=list)),
                ('time_stamp_api_call_s', models.JSONField(blank=True, default=list)),
                ('time_stamp_api_call_e', models.JSONField(blank=True, default=list)),
                ('retry_time_stamp_api', models.JSONField(blank=True, default=list)),
                ('api_call_e', models.DateTimeField(blank=True, null=True)),
                ('transaction_awaiting_time', models.DateTimeField(blank=True, null=True)),
                ('document_upload_s', models.JSONField(blank=True, default=list)),
                ('each_document_upload_s', models.JSONField(blank=True, default=list)),
                ('each_document_upload_e', models.JSONField(blank=True, default=list)),
                ('document_upload_e', models.JSONField(blank=True, default=list)),
                ('retry_document_upload_time', models.JSONField(blank=True, default=list)),
                ('assembly_process_e', models.DateTimeField(blank=True, null=True)),
                ('re_process_extraction_s', models.DateTimeField(blank=True, null=True)),
                ('re_process_extraction_e', models.DateTimeField(blank=True, null=True)),
                ('re_process_api_s', models.DateTimeField(blank=True, null=True)),
                ('re_process_upload_doc_s', models.DateTimeField(blank=True, null=True)),
                ('re_process_upload_doc_e', models.DateTimeField(blank=True, null=True)),
                ('re_process_email_batches_e', models.DateTimeField(blank=True, null=True)),
                ('transaction_process_e', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Transaction Logs',
            },
        ),
    ]
