# Generated by Django 4.0.2 on 2024-12-08 23:19
# Standard migration is updated to keep existing value

from django.db import migrations, models


def convert_string_to_json_array(apps, schema_editor):
    EmailBatch = apps.get_model("core", "EmailBatch")

    # Update all existing records
    for instance in EmailBatch.objects.all():
        current_value = instance.shipment_status_url

        if current_value is None:
            instance.temp_shipment_status_url = []
        elif isinstance(current_value, str):
            # Properly convert the string to a JSON array
            instance.temp_shipment_status_url = [
                current_value
            ]  # Wrap the string in a list
        instance.save()


def reverse_json_to_string(apps, schema_editor):
    EmailBatch = apps.get_model("core", "EmailBatch")

    for instance in EmailBatch.objects.all():
        if (
            isinstance(instance.shipment_status_url, list)
            and len(instance.shipment_status_url) > 0
        ):
            instance.temp_shipment_status_url = instance.shipment_status_url[0]
        else:
            instance.temp_shipment_status_url = ""
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_transactionlog"),
    ]

    operations = [
        # First, create a temporary field
        migrations.AddField(
            model_name="emailbatch",
            name="temp_shipment_status_url",
            field=models.JSONField(default=list, null=True),
        ),
        # Then run the data migration
        migrations.RunPython(convert_string_to_json_array, reverse_json_to_string),
        # Remove the old field
        migrations.RemoveField(
            model_name="emailbatch",
            name="shipment_status_url",
        ),
        # Rename the new field to the original name
        migrations.RenameField(
            model_name="emailbatch",
            old_name="temp_shipment_status_url",
            new_name="shipment_status_url",
        ),
    ]
