# Generated by Django 4.0.2 on 2024-12-16 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_alter_emailbatch_shipment_status_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbatch',
            name='shipment_status_url',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
