# Generated by Django 4.0.2 on 2025-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_alter_emailbatch_shipment_status_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailbatch',
            name='email_from',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
