# Generated by Django 5.1.4 on 2025-05-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_shipmentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='definition_id',
            field=models.CharField(blank=True, help_text='Profile Name', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='name_matching_text',
            field=models.CharField(default='', help_text='Profile Document Name Mathcing text', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='type',
            field=models.CharField(blank=True, help_text='Profile Document Type', max_length=100, null=True),
        ),
    ]
