# Generated by Django 5.1.4 on 2025-05-02 12:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_batch_definition_id_and_more'),
        ('dashboard', '0046_remove_profile_customer_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_id_type_and_name_matching',
        ),
        migrations.AlterField(
            model_name='definition',
            name='definition_id',
            field=models.CharField(help_text='Profile Name', max_length=254),
        ),
        migrations.AlterField(
            model_name='definition',
            name='name_matching_text',
            field=models.CharField(default='', help_text='Profile Document Name Mathcing text', max_length=100),
        ),
        migrations.AlterField(
            model_name='definition',
            name='type',
            field=models.CharField(help_text='Profile Document Type', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('definition_id'), django.db.models.functions.text.Lower('vendor'), django.db.models.functions.text.Lower('type'), django.db.models.functions.text.Lower('name_matching_text'), name='unique_definition_id_vendor_type_and_name_matching'),
        ),
    ]
