# Generated by Django 5.1.4 on 2025-05-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_remove_definition_unique_definition_id_type_and_name_matching_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='definition',
            name='name_matching_text',
            field=models.CharField(blank=True, default='', help_text='Profile Document Name Mathcing text', max_length=100, null=True),
        ),
    ]
