# Generated by Django 5.1.4 on 2025-05-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_alter_definition_name_matching_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailparseddocument',
            name='ra_json_created',
            field=models.BooleanField(default=False),
        ),
    ]
