# Generated by Django 5.1.4 on 2025-05-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_emailparseddocument_ra_json_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainparseddocument',
            name='ra_json_created',
            field=models.BooleanField(default=False),
        ),
    ]
