# Generated by Django 5.1.4 on 2025-05-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_trainparseddocument_ra_json_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
