# Generated by Django 5.1.4 on 2025-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_batch_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='parsed_file_type',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
