# Generated by Django 5.1.4 on 2025-05-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0100_emailbatch_parsed_file_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiAgentConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('user', 'user'), ('agent', 'agent')], max_length=10)),
                ('message', models.JSONField(default=dict)),
                ('event_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'AI Agent Conversations',
            },
        ),
    ]
