# Generated by Django 5.1.4 on 2025-05-24 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0101_aiagentconversation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='name_matching_text',
            field=models.CharField(blank=True, default='', help_text='Profile Document Name Mathcing text', max_length=100),
        ),
        migrations.AlterField(
            model_name='batch',
            name='sub_path',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
