# Generated by Django 5.1.4 on 2025-05-25 13:05

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_alter_batch_name_matching_text_alter_batch_sub_path'),
        ('dashboard', '0049_alter_project_settings'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_id_vendor_type_and_name_matching',
        ),
        migrations.AlterField(
            model_name='definition',
            name='type',
            field=models.CharField(blank=True, help_text='Profile Document Type', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('definition_id'), django.db.models.functions.text.Lower('vendor'), name='unique_definition_id_and_vendor'),
        ),
    ]
