# Generated by Django 5.1.4 on 2025-05-22 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0103_remove_definition_unique_definition_id_vendor_type_and_name_matching_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='emailbatch',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
