# Generated by Django 5.1.4 on 2025-07-13 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_emailbatch_content_type_emailbatch_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailbatch',
            name='force_ocr_engine',
            field=models.BooleanField(default=False),
        ),
    ]
