# Generated by Django 5.1.4 on 2025-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_emailbatch_force_ocr_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbatch',
            name='force_ocr_engine',
            field=models.BooleanField(default=False),
        ),
    ]
