# Generated by Django 5.1.4 on 2025-08-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0106_trainbatch_force_ocr_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentconversation',
            name='type',
            field=models.CharField(choices=[('timeline', 'timeline'), ('user', 'user'), ('agent', 'agent')], max_length=10),
        ),
    ]
