# Generated by Django 5.1.4 on 2025-08-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_alter_aiagentconversation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiagentconversation',
            name='type',
            field=models.CharField(choices=[('timeline', 'timeline'), ('user', 'user'), ('agent', 'agent'), ('reasoning', 'reasoning')], max_length=10),
        ),
    ]
