# Generated by Django 5.1.4 on 2025-08-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_alter_aiagentconversation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiagentconversation',
            name='transaction_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
