# Generated by Django 5.1.4 on 2025-09-09 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_batch_is_dataset_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='layout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='definition',
            name='layout_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
