# Generated by Django 5.1.4 on 2025-09-09 09:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_batch_layout_id_definition_layout_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_id_and_vendor',
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('definition_id'), django.db.models.functions.text.Lower('layout_id'), name='unique_definition_id_and_layout_id'),
        ),
    ]
