# Generated by Django 5.1.4 on 2025-09-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_remove_definition_unique_definition_id_and_vendor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='layout_id',
        ),
        migrations.AddField(
            model_name='batch',
            name='layout_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
