# Generated by Django 5.1.4 on 2025-09-11 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_remove_batch_layout_id_batch_layout_ids'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('DOWNLOAD', 'Download'), ('UPLOAD', 'Upload'), ('EXPORT', 'Export'), ('IMPORT', 'Import')], max_length=100)),
                ('module', models.CharField(choices=[('PROJECT', 'Project'), ('PROFILE', 'Profile')], max_length=100)),
                ('module_id', models.CharField(blank=True, max_length=100, null=True)),
                ('module_object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('object_name', models.CharField(blank=True, max_length=255, null=True)),
                ('change_category', models.CharField(blank=True, max_length=100, null=True)),
                ('old_data_path', models.CharField(blank=True, max_length=255, null=True)),
                ('new_data_path', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_reverted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['module', 'module_id'], name='core_change_module_0751fc_idx')],
            },
        ),
    ]
