# Generated by Django 5.1.4 on 2025-10-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_changelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='raw_data_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
