# Generated by Django 5.1.4 on 2025-11-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_batch_raw_data_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbatch',
            name='selected_doc_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
