# Generated by Django 5.1.4 on 2025-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_trainbatch_selected_doc_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='definition',
            name='hash_layout',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
