# Generated by Django 5.1.4 on 2025-11-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_definition_hash_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
    ]
