# Generated by Django 5.1.4 on 2025-12-03 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_definition_embedding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailparseddocument',
            name='doc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
