# Generated by Django 5.1.4 on 2026-01-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_emailparseddocument_doc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainbatch',
            name='custom_data',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='trainbatch',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
