# Generated by Django 5.1.4 on 2026-01-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_trainbatch_custom_data_trainbatch_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainbatch',
            name='custom_data',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainbatch',
            name='customer',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
