# Generated by Django 4.0.2 on 2023-06-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_profile_created_at_profile_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
