# Generated by Django 4.0.2 on 2023-07-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_alter_profile_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="barcode",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email_domains",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email_from",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="email_subject_match_text",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="ocr_engine",
            field=models.CharField(
                choices=[("S", "S"), ("P", "P"), ("A", "A")],
                default=False,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="page_rotate",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
