# Generated by Django 4.0.2 on 2023-07-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0004_profile_barcode_profile_email_domains_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_subject_match_option",
            field=models.CharField(
                choices=[
                    ("StartsWith", "StartsWith"),
                    ("EndsWith", "EndsWith"),
                    ("Contains", "Contains"),
                ],
                default="StartsWith",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
