# Generated by Django 4.0.2 on 2023-07-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_profile_email_subject_match_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doc_type", models.CharField(max_length=255)),
                (
                    "name_matching_option",
                    models.CharField(
                        choices=[
                            ("StartsWith", "StartsWith"),
                            ("EndsWith", "EndsWith"),
                            ("Contains", "Contains"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name_matching_text", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Processing", "Processing"),
                            ("Supporting", "Supporting"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "language",
                    models.CharField(choices=[("English", "English")], max_length=50),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="dashboard.profile",
                    ),
                ),
            ],
        ),
    ]
