# Generated by Django 4.0.2 on 2023-07-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0006_profiledocument"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="barcode",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="ocr_engine",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="page_rotate",
        ),
        migrations.AddField(
            model_name="profiledocument",
            name="barcode",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profiledocument",
            name="content_location",
            field=models.CharField(
                choices=[
                    ("Email Body", "Email Body"),
                    ("Email Attachment", "Email Attachment"),
                ],
                default="Email Attachment",
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profiledocument",
            name="ocr_engine",
            field=models.CharField(
                choices=[("S", "S"), ("P", "P"), ("A", "A")],
                default=False,
                max_length=30,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profiledocument",
            name="page_rotate",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profiledocument",
            name="name_matching_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("StartsWith", "StartsWith"),
                    ("EndsWith", "EndsWith"),
                    ("Contains", "Contains"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profiledocument",
            name="name_matching_text",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
