# Generated by Django 4.0.2 on 2023-07-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0007_remove_profile_barcode_remove_profile_ocr_engine_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="exception_handling",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="project",
            field=models.CharField(max_length=30),
        ),
    ]
