# Generated by Django 4.0.2 on 2023-07-24 06:59

import django.db.models.expressions
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_profile_exception_handling_alter_profile_project"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="profiledocument",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("profile"),
                django.db.models.functions.text.Lower("doc_type"),
                name="unique_profile_and_doc_type",
            ),
        ),
    ]
