# Generated by Django 4.0.2 on 2023-08-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0009_profiledocument_unique_profile_and_doc_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="replay_booking_additional_emails",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_booking_to_cc_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_booking_to_email_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reciept_additional_emails",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reciept_to_cc_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reciept_to_email_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reference_additional_emails",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reference_to_cc_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_reference_to_email_sender",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_subject",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_with_same_subject",
            field=models.BooleanField(default=True),
        ),
    ]
