# Generated by Django 4.0.2 on 2023-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0010_profile_replay_booking_additional_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="replay_failure_additional_emails",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_failure_to_cc_users",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="replay_failure_to_email_sender",
            field=models.BooleanField(default=False),
        ),
    ]
