# Generated by Django 4.0.2 on 2023-08-24 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0011_profile_replay_failure_additional_emails_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="replay_booking_additional_emails",
            new_name="reply_booking_additional_emails",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_booking_to_cc_users",
            new_name="reply_booking_to_cc_users",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_booking_to_email_sender",
            new_name="reply_booking_to_email_sender",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_failure_additional_emails",
            new_name="reply_failure_additional_emails",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_failure_to_cc_users",
            new_name="reply_failure_to_cc_users",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_failure_to_email_sender",
            new_name="reply_failure_to_email_sender",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reciept_additional_emails",
            new_name="reply_reciept_additional_emails",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reciept_to_cc_users",
            new_name="reply_reciept_to_cc_users",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reciept_to_email_sender",
            new_name="reply_reciept_to_email_sender",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reference_additional_emails",
            new_name="reply_reference_additional_emails",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reference_to_cc_users",
            new_name="reply_reference_to_cc_users",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_reference_to_email_sender",
            new_name="reply_reference_to_email_sender",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_subject",
            new_name="reply_subject",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="replay_with_same_subject",
            new_name="reply_with_same_subject",
        ),
    ]
