# Generated by Django 4.0.2 on 2023-08-25 04:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "dashboard",
            "0012_rename_replay_booking_additional_emails_profile_reply_booking_additional_emails_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="reply_reference_additional_emails",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reply_reference_to_cc_users",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="reply_reference_to_email_sender",
        ),
    ]
