# Generated by Django 4.0.2 on 2023-09-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0013_remove_profile_reply_reference_additional_emails_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledocument",
            name="name_matching_option",
            field=models.CharField(
                blank=True,
                choices=[
                    ("StartsWith", "StartsWith"),
                    ("EndsWith", "EndsWith"),
                    ("Contains", "Contains"),
                    ("Auto", "Auto"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
