# Generated by Django 4.0.2 on 2023-09-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0014_alter_profiledocument_name_matching_option"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledocument",
            name="language",
            field=models.CharField(max_length=50),
        ),
    ]
