# Generated by Django 4.0.2 on 2023-09-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0015_alter_profiledocument_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profiledocument",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Arabic", "Arabic"),
                    ("ChinesePRC", "ChinesePRC"),
                    ("ChineseTaiwan", "ChineseTaiwan"),
                    ("Czech", "Czech"),
                    ("Dutch", "Dutch"),
                    ("French", "French"),
                    ("German", "German"),
                    ("Greek", "Greek"),
                    ("Italian", "Italian"),
                    ("Japanese", "Japanese"),
                    ("Korean", "Korean"),
                    ("Norwegian", "Norwegian"),
                    ("Polish", "Polish"),
                    ("PortugueseBrazilian", "PortugueseBrazilian"),
                    ("PortugueseStandard", "PortugueseStandard"),
                    ("Russian", "Russian"),
                    ("Slovak", "Slovak"),
                    ("Slovenian", "Slovenian"),
                    ("Spanish", "Spanish"),
                    ("Swedish", "Swedish"),
                    ("Turkish", "Turkish"),
                ],
                max_length=50,
            ),
        ),
    ]
