# Generated by Django 4.0.2 on 2023-10-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_alter_profiledocument_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reply_booking_additional_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_booking_to_cc_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_booking_to_email_sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_failure_additional_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_failure_to_cc_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_failure_to_email_sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_reciept_additional_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_reciept_to_cc_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_reciept_to_email_sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reply_with_same_subject',
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notification_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notification_with_same_subject',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_additional_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_cc_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_email_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_email_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_failure_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='send_success_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notification_subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notification_with_same_subject',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_additional_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_cc_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_email_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_email_sender',
            field=models.BooleanField(default=False),
        ),
    ]
