# Generated by Django 4.0.2 on 2023-10-17 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_remove_profile_reply_booking_additional_emails_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='exception_handling',
            new_name='manual_validation',
        ),
    ]
