# Generated by Django 4.0.2 on 2023-10-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_exception_handling_profile_manual_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_subject_match_option',
            field=models.CharField(choices=[('StartsWith', 'StartsWith'), ('EndsWith', 'EndsWith'), ('Contains', 'Contains'), ('Regex', 'Regex')], max_length=50),
        ),
    ]
