# Generated by Django 4.0.2 on 2023-10-30 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_alter_profile_email_subject_match_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='send_failure_notification',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='send_success_notification',
        ),
    ]
