# Generated by Django 4.0.2 on 2023-12-05 06:27

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='definition_settings',
            field=models.JSONField(default=dashboard.models.get_default_definition_settings),
        ),
    ]
