# Generated by Django 4.0.2 on 2024-02-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0022_alter_project_definition_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_domains',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_from',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
