# Generated by Django 4.0.2 on 2024-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_alter_profile_email_domains_alter_profile_email_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=2),
        ),
    ]
