# Generated by Django 4.0.2 on 2024-03-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0024_alter_profile_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="profiledocument",
            name="show_embedded_img",
            field=models.BooleanField(default=False),
        ),
    ]
