# Generated by Django 4.0.2 on 2024-05-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0025_profiledocument_show_embedded_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="email_box",
            field=models.CharField(
                default="username@domain.com", max_length=255, null=True
            ),
        ),
    ]
