# Generated by Django 4.0.2 on 2024-05-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0026_project_emial_box"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="email_box",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
