# Generated by Django 4.0.2 on 2024-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_alter_profiledocument_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_time_stamp',
            field=models.BooleanField(default=False),
        ),
    ]
