# Generated by Django 4.0.2 on 2024-06-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_profile_send_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
                ('doc_type', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=2)),
                ('file_type', models.CharField(choices=[('.xlsx', '.xlsx')], max_length=30)),
                ('language', models.CharField(choices=[('English', 'English'), ('Arabic', 'Arabic'), ('ChinesePRC', 'ChinesePRC'), ('ChineseTaiwan', 'ChineseTaiwan'), ('Czech', 'Czech'), ('Dutch', 'Dutch'), ('French', 'French'), ('German', 'German'), ('Greek', 'Greek'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Norwegian', 'Norwegian'), ('Polish', 'Polish'), ('PortugueseBrazilian', 'PortugueseBrazilian'), ('PortugueseStandard', 'PortugueseStandard'), ('Russian', 'Russian'), ('Slovak', 'Slovak'), ('Slovenian', 'Slovenian'), ('Spanish', 'Spanish'), ('Swedish', 'Swedish'), ('Turkish', 'Turkish'), ('None', 'None')], max_length=50)),
                ('category', models.CharField(default='Processing', max_length=50)),
                ('ocr_engine', models.CharField(choices=[('S', 'S'), ('P', 'P'), ('A', 'A')], max_length=30)),
                ('page_rotate', models.BooleanField()),
                ('barcode', models.BooleanField()),
                ('use_existing_definition', models.BooleanField()),
                ('existing_profile_name', models.CharField(default='', max_length=255, null=True)),
                ('existing_document', models.CharField(default='', max_length=255, null=True)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('linked_batches', models.JSONField(blank=True, default=list)),
                ('linked_profiles', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeline_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_message', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('event_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='profiledocument',
            name='template',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
