# Generated by Django 4.0.2 on 2024-07-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_template_timeline_profiledocument_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='automatic_splitting',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='ignore_dense_pages',
            field=models.BooleanField(default=False),
        ),
    ]
