# Generated by Django 4.0.2 on 2024-07-18 16:53

from django.db import migrations, models
import django.db.models.expressions
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0031_profile_automatic_splitting_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profiledocument',
            name='unique_profile_and_doc_type',
        ),
        migrations.AddConstraint(
            model_name='profiledocument',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('profile'), django.db.models.functions.text.Lower('doc_type'), django.db.models.functions.text.Lower('name_matching_text'), name='unique_profile_doc_type_and_name_matching'),
        ),
    ]
