# Generated by Django 4.0.2 on 2024-07-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_remove_profiledocument_unique_profile_and_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledocument',
            name='content_location',
            field=models.CharField(choices=[('Email Body', 'Email Body'), ('Email Attachment', 'Email Attachment'), ('Additional Document', 'Additional Document')], max_length=50),
        ),
    ]
