# Generated by Django 4.0.2 on 2024-08-04 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_alter_profiledocument_content_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledocument',
            name='category',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Supporting', 'Supporting'), ('Ignoring', 'Ignoring')], max_length=50),
        ),
    ]
