# Generated by Django 4.0.2 on 2024-08-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0034_alter_profiledocument_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiledocument',
            name='name_matching_option',
            field=models.CharField(blank=True, choices=[('StartsWith', 'StartsWith'), ('EndsWith', 'EndsWith'), ('Contains', 'Contains'), ('Regex', 'Regex'), ('Auto', 'Auto')], max_length=50, null=True),
        ),
    ]
