# Generated by Django 4.0.2 on 2024-06-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0035_alter_profiledocument_name_matching_option",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="manual_classification",
            field=models.BooleanField(default=False),
        ),
    ]
