# Generated by Django 4.0.2 on 2024-10-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_profile_manual_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mode_of_transport',
            field=models.CharField(choices=[('AIR', 'AIR'), ('COU', 'COU'), ('SEA', 'SEA'), ('RAI', 'RAI'), ('ROA', 'ROA'), ('ALL', 'ALL')], max_length=5),
        ),
    ]
