# Generated by Django 4.0.2 on 2024-10-04 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0037_alter_profile_mode_of_transport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="manual_classification",
        ),
    ]
