# Generated by Django 4.0.2 on 2024-11-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_remove_profile_manual_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='multi_shipment',
            field=models.BooleanField(default=False),
        ),
    ]
