# Generated by Django 4.0.2 on 2025-01-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_profile_multi_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exceptional_excel',
            field=models.BooleanField(default=False),
        ),
    ]
