# Generated by Django 4.0.2 on 2025-01-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_profile_exceptional_excel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_domains',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_from',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
