# Generated by Django 4.0.2 on 2025-01-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0041_alter_profile_email_domains_alter_profile_email_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="file_type",
            field=models.CharField(
                choices=[(".xlsx", ".xlsx"), (".xls", ".xls")], max_length=30
            ),
        ),
    ]
