# Generated by Django 4.0.2 on 2025-02-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_alter_template_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_domains',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_from',
            field=models.CharField(blank=True, max_length=8000, null=True),
        ),
    ]
