# Generated by Django 4.0.2 on 2025-01-31 07:32

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0043_alter_profile_email_domains_alter_profile_email_from"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeveloperSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(default=dict)),
                (
                    "default_settings",
                    models.JSONField(
                        default=dashboard.models.get_predefined_dev_settings
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Developer Settings",
            },
        ),
    ]
