# Generated by Django 5.1.4 on 2025-05-02 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_developersettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='definition_settings',
        ),
        migrations.AddField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
