# Generated by Django 5.1.4 on 2025-05-02 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_project_definition_settings_project_settings_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notification_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notification_with_same_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notify_additional_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notify_cc_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notify_email_recipients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='failure_notify_email_sender',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notification_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notification_with_same_subject',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notify_additional_emails',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notify_cc_users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notify_email_recipients',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='success_notify_email_sender',
        ),
        migrations.AddField(
            model_name='profile',
            name='keys',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ProfileCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=40)),
                ('success_notification_with_same_subject', models.BooleanField(default=True)),
                ('success_notification_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('success_notify_email_sender', models.BooleanField(default=False)),
                ('success_notify_email_recipients', models.BooleanField(default=False)),
                ('success_notify_cc_users', models.BooleanField(default=False)),
                ('success_notify_additional_emails', models.CharField(blank=True, max_length=500, null=True)),
                ('failure_notification_with_same_subject', models.BooleanField(default=True)),
                ('failure_notification_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('failure_notify_email_sender', models.BooleanField(default=False)),
                ('failure_notify_email_recipients', models.BooleanField(default=False)),
                ('failure_notify_cc_users', models.BooleanField(default=False)),
                ('failure_notify_additional_emails', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='dashboard.profile')),
            ],
        ),
    ]
