# Generated by Django 5.1.4 on 2025-05-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_remove_profile_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='free_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
