# Generated by Django 5.1.4 on 2025-05-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_profile_free_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default={'compoundKeys': [], 'editableOptions': ['options-col-type', 'options-col-modType', 'options-keys', 'options-meta-root-type'], 'keyQualifiers': [], 'options': {'options-col-modType': {'fields': [{'key': 'mandatory', 'type': 'checkbox'}, {'key': 'modType', 'type': 'text'}, {'key': 'description', 'type': 'text'}], 'items': [], 'lableKey': 'modType', 'title': 'modType', 'valueKey': 'modType'}, 'options-col-type': {'fields': [{'key': 'mandatory', 'type': 'checkbox'}, {'key': 'type', 'type': 'text'}, {'key': 'applicableForKeys', 'type': 'checkbox'}, {'key': 'applicableForTable', 'type': 'checkbox'}, {'key': 'description', 'type': 'text'}], 'items': [], 'lableKey': 'type', 'title': 'type', 'valueKey': 'type'}, 'options-keys': {'fields': [{'key': 'keyLabel', 'type': 'text'}, {'key': 'keyValue', 'type': 'text'}, {'key': 'type', 'optionsId': 'options-col-type', 'type': 'select'}, {'key': 'qualifier', 'type': 'qualifier'}, {'key': 'modType', 'optionsId': 'options-col-modType', 'type': 'select'}, {'key': 'compoundKeys', 'type': 'compoundKeys'}, {'key': 'export', 'type': 'checkbox'}], 'items': [], 'lableKey': 'keyLabel', 'sortBy': 'keyLabel', 'title': 'keys', 'valueKey': 'keyValue'}, 'options-meta-root-type': {'fields': [{'key': 'docType', 'type': 'text'}, {'key': 'docNumber', 'type': 'text'}], 'items': [], 'lableKey': 'docType', 'title': 'docType', 'valueKey': 'docType'}}}),
        ),
    ]
