# Generated by Django 5.1.4 on 2025-05-06 06:44

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_alter_project_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='settings',
            field=models.JSONField(blank=True, default=dashboard.models.get_default_definition_settings),
        ),
    ]
