# Generated by Django 5.1.4 on 2025-07-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_alter_project_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='email_box',
        ),
    ]
