# Generated by Django 5.1.4 on 2025-08-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_remove_project_email_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilecustomer',
            old_name='address',
            new_name='address_line1',
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='address_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='address_line2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='short_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
