# Generated by Django 5.1.4 on 2025-08-07 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0051_rename_address_profilecustomer_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilecustomer',
            name='org_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profilecustomer',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
