# Generated by Django 5.1.4 on 2025-08-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_profilecustomer_org_name_profilecustomer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
