# Generated by Django 5.1.4 on 2025-08-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_alter_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='translated_documents',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
