# Generated by Django 5.1.4 on 2025-08-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_profile_translated_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_id']},
        ),
        migrations.AddField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID in format AA1-ZZ9', max_length=3),
        ),
    ]
