# Generated by Django 5.1.4 on 2025-09-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_populate_project_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='process_id',
            field=models.CharField(blank=True, help_text='Auto-generated ID in format AF-AA1-1234567', max_length=14),
        ),
    ]
