# Generated by Django 5.1.4 on 2025-09-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_populate_process_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_subject_match_option',
            field=models.CharField(choices=[('ProcessId', 'ProcessId'), ('StartsWith', 'StartsWith'), ('EndsWith', 'EndsWith'), ('Contains', 'Contains'), ('Regex', 'Regex')], max_length=50),
        ),
    ]
