# Generated by Django 5.1.4 on 2025-09-16 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_alter_profile_email_subject_match_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutputChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('auth_type', models.CharField(choices=[('none', 'No Auth'), ('basic', 'Basic Auth'), ('token', 'Token Auth'), ('api_key', 'API Key in Header'), ('oauth2', 'OAuth2 Bearer Token')], default='none', max_length=20)),
                ('endpoint_url', models.CharField(blank=True, max_length=500, null=True)),
                ('_username', models.TextField(blank=True, null=True)),
                ('_password', models.TextField(blank=True, null=True)),
                ('_token', models.TextField(blank=True, null=True)),
                ('api_key_name', models.CharField(blank=True, max_length=100, null=True)),
                ('_api_key_value', models.TextField(blank=True, null=True)),
                ('_client_id', models.CharField(blank=True, max_length=255, null=True)),
                ('_client_secret', models.TextField(blank=True, null=True)),
                ('token_url', models.CharField(blank=True, max_length=500, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output_channels', to='dashboard.project')),
            ],
        ),
    ]
