# Generated by Django 5.1.4 on 2025-09-17 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0060_outputchannel'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputchannel',
            name='request_type',
            field=models.CharField(default='POST', max_length=12),
        ),
    ]
