# Generated by Django 5.1.4 on 2025-10-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0061_outputchannel_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputchannel',
            name='output_type',
            field=models.CharField(choices=[('json', 'JSON'), ('document', 'DOCUMENT')], default='json', max_length=20),
        ),
        migrations.AlterField(
            model_name='outputchannel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_channels', to='dashboard.project'),
        ),
        migrations.AlterUniqueTogether(
            name='outputchannel',
            unique_together={('project', 'output_type')},
        ),
    ]
