# Generated by Django 5.1.4 on 2025-10-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_outputchannel_output_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='mode_of_transport',
        ),
    ]
