# Generated by Django 5.1.4 on 2025-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0063_remove_profile_mode_of_transport'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lookup_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
