# Generated by Django 5.1.4 on 2025-10-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_profile_lookup_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parties_config',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
