# Generated by Django 5.1.4 on 2025-10-22 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0065_profile_parties_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='process_id',
            field=models.CharField(help_text='Auto-generated ID in format COUNTRY-PROJECT_ID-NUMBER (e.g., AF-AA1-0000001)', max_length=14, unique=True),
        ),
    ]
