# Generated by Nayem on 2025-10-22 00:54

from django.db import migrations, models
from collections import defaultdict


def migrate_process_ids_forward(apps, schema_editor):
    """
    Migrate ALL process_ids to new format starting from 1.
    Old format: COUNTRY-PROJECT_ID-1234567
    New format: COUNTRY-PROJECT_ID-0000001
    """
    Profile = apps.get_model('dashboard', 'Profile')
    Project = apps.get_model('dashboard', 'Project')
    
    # Profiles WITH process_id (sorted)
    profiles_with_id = Profile.objects.exclude(
        models.Q(process_id__isnull=True) | models.Q(process_id='')
    ).order_by('process_id')

    # Profiles WITHOUT process_id (empty/null)
    profiles_without_id = Profile.objects.filter(
        models.Q(process_id__isnull=True) | models.Q(process_id='')
    ).order_by('created_at')

    # Combine: WITH first, WITHOUT second
    all_profiles = list(profiles_with_id) + list(profiles_without_id)
    
    total_count = len(all_profiles)
    if total_count == 0:
        print("No profiles found. Nothing to migrate.")
        return
    
    print(f"Found {total_count} profile(s) to migrate")
    
    # Group profiles by country-project combination
    grouped_profiles = defaultdict(list)
    for profile in all_profiles:
        country = profile.country.upper() if profile.country else 'AF'
        
        # Get project instance using the project field from profile
        try:
            project = Project.objects.get(name=profile.project)
            project_id = project.project_id
        except Project.DoesNotExist:
            # Handle case where project doesn't exist
            print(f"Warning: Project '{profile.project}' not found for profile {profile.id}")
            project_id = 'AA1'  # Default fallback

        key = f"{country}-{project_id}"
        grouped_profiles[key].append(profile)
    
    # Process each group
    updates_count = 0
    for prefix, profile_list in sorted(grouped_profiles.items()):
        print(f"Processing group: {prefix} ({len(profile_list)} profiles)")
        
        # Start numbering from 1 for each group
        next_number = 1
        
        for profile in profile_list:
            old_process_id = profile.process_id
            new_process_id = f"{prefix}-{next_number:07d}"
            
            # Only update if the process_id has changed
            if old_process_id != new_process_id:
                profile.process_id = new_process_id
                profile.save(update_fields=['process_id'])
                print(f"  Updated Profile {profile.id}: {old_process_id} → {new_process_id}")
                updates_count += 1
            else:
                print(f"  Skipped Profile {profile.id}: Already has correct format {new_process_id}")
            
            next_number += 1
    
    print(f"✓ Successfully updated {updates_count} profile(s)")


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0066_alter_profile_process_id'),
    ]

    operations = [
        migrations.RunPython(
            migrate_process_ids_forward,
            reverse_code=migrations.RunPython.noop
        ),
    ]