# Generated by Django 5.1.4 on 2025-10-21 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0067_migrate_profile_process_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outputchannel',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='outputchannel',
            name='output_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
