# Generated by Django 5.1.4 on 2025-01-05 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0068_alter_outputchannel_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dictionaries',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
