# Generated by Django 5.1.4 on 2025-12-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0069_profile_dictionaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failure_notify_email_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_email_sender',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_email_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_email_sender',
            field=models.BooleanField(default=False),
        ),
    ]
