# Generated by Django 5.1.4 on 2025-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0070_profile_failure_notify_email_recipients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='failure_notify_additional_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='failure_notify_exclude_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_additional_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='success_notify_exclude_emails',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
