# Generated by Django 5.1.4 on 2026-01-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0071_profile_failure_notify_additional_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='project',
            field=models.CharField(max_length=255),
        ),
    ]
