# Generated by Django 5.1.4 on 2026-01-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0072_alter_profile_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lookup_items',
        ),
    ]
