# Generated by Django 5.1.4 on 2026-02-03 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0074_processcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='outputchannel',
            name='grant_type',
            field=models.CharField(choices=[('password', 'Password'), ('client_credentials', 'Client Credentials')], default='client_credentials', max_length=100),
        ),
        migrations.AddField(
            model_name='outputchannel',
            name='scope',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
