# Generated by Django 5.1.4 on 2026-02-04

import re
import uuid
from collections import Counter
from django.db import migrations, models


_INVALID_IDENTIFIER_CHARS = re.compile(r"[^0-9A-Za-z_-]+")
_REPEATED_SEPARATORS = re.compile(r"[_-]{2,}")


def _normalize_process_name(raw_name: str, max_length: int = 128) -> str:
    cleaned = str(raw_name or "").strip()
    if not cleaned:
        return ""
    cleaned = _INVALID_IDENTIFIER_CHARS.sub("_", cleaned)
    cleaned = _REPEATED_SEPARATORS.sub("_", cleaned)
    cleaned = cleaned.strip("_-")
    if not cleaned:
        return ""
    if len(cleaned) > max_length:
        cleaned = cleaned[:max_length]
    return cleaned


def backfill_process_uid(apps, schema_editor):
    Profile = apps.get_model("dashboard", "Profile")
    namespace = "internal_vector_database_legacy_process"

    profiles = []
    normalized_names = []
    for profile in Profile.objects.all().only("id", "name", "free_name"):
        process_name = (profile.name or profile.free_name or "").strip()
        normalized_name = _normalize_process_name(process_name)
        profiles.append((profile, normalized_name))
        if normalized_name:
            normalized_names.append(normalized_name)

    name_counts = Counter(normalized_names)

    for profile, normalized_name in profiles:
        if not normalized_name or name_counts.get(normalized_name, 0) > 1:
            profile.process_uid = uuid.uuid4()
        else:
            profile.process_uid = uuid.uuid5(
                uuid.NAMESPACE_DNS, f"{namespace}:{normalized_name}"
            )
        profile.save(update_fields=["process_uid"])


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0075_outputchannel_grant_type_outputchannel_scope"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="process_uid",
            field=models.UUIDField(
                blank=True,
                null=True,
                unique=True,
                editable=False,
                help_text="Immutable unique identifier for Qdrant and internal references",
            ),
        ),
        migrations.RunPython(backfill_process_uid, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="profile",
            name="process_uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                editable=False,
                help_text="Immutable unique identifier for Qdrant and internal references",
            ),
        ),
    ]
